version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  relink:
    image: edwin503/relink:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - RELINK_PREFIX=http://localhost/
      - SERVER_PORT=80
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
volumes:
  pg_data: